### ISSUE TITLE
mingw-w64-qt5-base-dynamic: Variable QMAKE_DEFAULT_INCDIRS and QMAKE_DEFAULT_LIBDIRS is not defined.

### ISSUE THREAD

**Issue by hipersayanX** [Martchus/PKGBUILDs#42] opened 2017-09-16 00:36 UTC
When compiling a project I get this message in both i686 and x86_64:

    /usr/i686-w64-mingw32/lib/qt/mkspecs/features/toolchain.prf:95: Variable QMAKE_DEFAULT_INCDIRS is not defined.
    /usr/i686-w64-mingw32/lib/qt/mkspecs/features/toolchain.prf:96: Variable QMAKE_DEFAULT_LIBDIRS is not defined.

Even so the project still compiles and works well, and _qmake -query_ give the right paths.

**Comment by Martchus** [comment] 2017-09-16 11:55
I am aware of this warning but didn't care much so far, because it doesn't seem to cause any problems. But I can have a look at it again when updating anyways.

**Comment by Martchus** [comment] 2018-01-08 13:51
This issue is caused by https://github.com/Martchus/qtbase/commit/440c61802ae80ceda51ed8d405ab922dddaa2d45. I didn't initially write this patch (only rebased it a few times) and don't know anymore which bug that patch was supposed to fix. So I'll just try to drop it when updating the mingw-w64 Qt 5 packages anyways: https://github.com/Martchus/qtbase/tree/5.10.0-mingw-w64-fixes

**Comment by Martchus** [comment] 2018-02-19 19:12
Should be fixed with https://github.com/Martchus/PKGBUILDs/commit/11f8ccba192f99af8b8126badc82af8d8075735b.

**Closed by Martchus** 2018-02-19 19:12 UTC
Labels: bug
