### ISSUE TITLE
Statically linking against Qt5 messes with zlib.dll

### ISSUE THREAD

**Issue by ypnos** [Martchus/PKGBUILDs#86] opened 2019-03-05 19:11 UTC
This behavior is pretty recent, however I cannot pinpoint the package version. I am building my software both with qmake and CMake (I am transitioning).

With qmake, both `libz.dll.a` and `libz.a` are linked. The linker complains about multiple definitions; the binary links and works fine if I remove the former from Makefile.release. Here the relevant snippet from the file (I shortened paths here for better readability):

> … -lQt5Widgets **/lib/libz.dll.a** /lib/libQt5Widgets.a -lQt5Gui -ldwmapi -luxtheme /lib/libQt5Gui.a -lQt5Core /lib/libpng16.a /lib/libfreetype.a /lib/libharfbuzz.a /lib/libglib-2.0.a /lib/libws2_32.a /lib/libole32.a /lib/libwinmm.a /lib/libshlwapi.a /lib/libpcre.a /lib/libintl.a /lib/libgraphite2.a /lib/libbz2.a /lib/libglu32.a /lib/libopengl32.a /lib/libgdi32.a /lib/libuser32.a -lopengl32 -lgdi32 -lcomdlg32 -loleaut32 -limm32 -ljpeg -lpng -lharfbuzz -lm -lglib-2.0 -lintl -lshlwapi -lpcre -lgraphite2 -lfreetype -lbz2 /lib/libQt5Core.a -lmpr **/lib/libz.a** …

With CMake, everything compiles and links without intervention. However, the executable then is dynamically linked to `zlib1.dll` and therefore cannot run without it.

My qmake file is pretty much standard, all I do there is `CONFIG += static` for static build.
In CMake, I found different solutions to building statically than you did [here][1]. I only do a couple things different to dynamic build:
```cmake
set(CMAKE_EXE_LINKER_FLAGS "-static")
set(CMAKE_FIND_LIBRARY_SUFFIXES ".a" CONFIG)
set(USE_STATIC_QT_BY_DEFAULT ON)
```

In target_link_libraries, I can include without penalty the plugins for both dynamic/static:
```cmake
target_link_libraries(helloworld PUBLIC
	Qt5::Widgets Qt5::Charts Qt5::Svg
	Qt5::QSvgIconPlugin
	Qt5::QWindowsIntegrationPlugin Qt5::QWindowsVistaStylePlugin
	)
```

Your source ([1]) was the _only_ one I found in extensive research that told me I need to add the `IMPORT_PLUGIN` lines to the sources. Thank you for that!

[1]: https://github.com/oggio88/Qt-CMake-HelloWorld/compare/master...Martchus:mingw-w64-static

**Comment by Martchus** [comment] 2019-03-05 20:27
Read [my note about the Qt 5.12.1 update](https://aur.archlinux.org/packages/mingw-w64-qt5-base#comment-680740). So the relevant package version change is Qt 5.12.0 to Qt 5.12.1. They changed the library resolution to add the full path to the linker line (at least in some cases) which broke my hacks to "support" a fully statically linked build.

But I thought I would have been fixed the issues. I came to that conclusion because `mingw-w64-qt5-tools` built for me. (The build process of that package contains multiple statically linked applications built with qmake - although the final package only contains the dynamically linked versions.) Not sure what's different in your case.

Also the packages `mingw-w64-passwordmanager-static` and `mingw-w64-tageditor-static` could be build. Those use CMake and I didn't end up with a binary depending on dynamic zlib. However, I was using the static targets explicitly here (e.g. `StaticQt5::Widgets`) instead of `set(USE_STATIC_QT_BY_DEFAULT ON)`. Maybe using the `set(USE_STATIC_QT_BY_DEFAULT ON)` is buggy. So do at least the `StaticQt5::*` targets work?

Do you use the version from my binary repository or did you build your one version? If you built it on your own I hope you've been building in a clean chroot with `makechrootpkg`. Otherwise you might have built the new version while the old one was still installed. That *could* cause problems of that kind.

By the way: The problem is that Qt doesn't officially support a *fully* statically linked build for the mingw-w64 platform. So this is basically just "a hack". They also don't support installing a static build and a dynamic build in the same prefix. That's also just a hack. (I actually want to get rid of that hack and just install into 2 different prefixes.) They also don't support using static plugins with CMake at all because transitive dependencies are not considered. That isn't even a mingw-w64 specific problem. I've ran into the same issue when trying to use a static Qt build for Mac OSX with CMake. So making static plugins work with CMake is also just another hack I've come up with. Too come to a conclusion: You shouldn't expect too much here. I hope it now becomes clear why your extensive research did not lead you to any official documentation and in fact all you've got was my example CMake file.

**Comment by ypnos** [comment] 2019-03-06 11:07
First of all, good news. Using StaticQt targets works as expected. It didn't configure in CMake for me before, but I must have made a mistake. Now I have a solution that works, great!

Thank you very much for your extensive efforts on this and also for your prompt and elaborate communication. Your work makes my life much easier and I am sure there are many others as well.

It appeared to me that "the Qt people" are not interested in supporting static builds of the _open source_ version of Qt, because of fear that people will (inadvertently/negligently?) violate LGPL. And there is probably zero _commercial licensees_ that cross-compile for Windows as they sell their products for that platform. So I assume we are caught between two stools here.

**Comment by Martchus** [comment] 2019-03-06 12:40
Good to hear. Likely I should still test the `USE_STATIC_QT_BY_DEFAULT`-way when I find the time.

> It appeared to me that "the Qt people" are not interested in supporting static builds of the open source version of Qt, because of fear that people will (inadvertently/negligently?) violate LGPL. 

I am not aware those ulterior motives but I also can not completely dismiss that deduction. However, so far it seems that mainly technical issues in their build system are preventing certain use-cases like ours.

I'd also like to note that they at least "kind of" support to build Qt itself as a static library. Only the fully statically linked build is not supported for mingw-w64 and static plugins don't work with CMake. The latter might improve in the future when they are transitioning to CMake. I also think that they support a fully statically linked build (of the open source version) if one uses Microsoft's compiler. Likely the Microsoft compiler is also what most of their customers use so that's what they focus on.

By the way, not even cross compilation itself (regardless of dynamic or static build) seems to be supported for the Windows platform. For instance the [discussion regarding my last fix](https://codereview.qt-project.org/#/c/251910) let me come to that conclusion.

**Comment by Martchus** [comment] 2019-03-07 09:12
Unfortunately I can reproduce the zlib issue when building Syncthing Tray. The `linklibs.rsp` is messed up:

```
linklibs.rsp
 -L/build/mingw-w64-syncthingtray-static/src/syncthingtray/build-i686-w64-mingw32/connector  -L/build/mingw-w64-syncthingtray-static/src/syncthingtray/build-i686-w64-mingw32/model  -L/build/mingw-w64-syncthingtray-static/src/lib -static -static-libstdc++ -static-libgcc /usr/i686-w64-mingw32/lib/libc++utilities.a /usr/i686-w64-mingw32/lib/libqtutilities.a ../connector/libsyncthingconnector.a ../model/libsyncthingmodel.a ../widgets/libsyncthingwidgets.a /usr/i686-w64-mingw32/lib/libQt5Network.a /usr/i686-w64-mingw32/lib/libQt5Widgets.a /usr/i686-w64-mingw32/lib/libQt5Core.a -Wl,-Bdynamic /usr/i686-w64-mingw32/lib/qt/plugins/platforms/libqwindows.a /usr/i686-w64-mingw32/lib/qt/plugins/styles/libqwindowsvistastyle.a /usr/i686-w64-mingw32/lib/qt/plugins/imageformats/libqgif.a /usr/i686-w64-mingw32/lib/qt/plugins/imageformats/libqico.a /usr/i686-w64-mingw32/lib/qt/plugins/imageformats/libqjpeg.a /usr/i686-w64-mingw32/lib/qt/plugins/imageformats/libqsvg.a /usr/i686-w64-mingw32/lib/qt/plugins/iconengines/libqsvgicon.a /usr/i686-w64-mingw32/lib/libc++utilities.a /usr/i686-w64-mingw32/lib/libQt5Gui.a ../model/libsyncthingmodel.a ../connector/libsyncthingconnector.a /usr/i686-w64-mingw32/lib/libQt5Network.a /usr/i686-w64-mingw32/lib/libQt5Core.a /usr/i686-w64-mingw32/lib/libc++utilities.a /usr/i686-w64-mingw32/lib/libqtutilities.a /usr/i686-w64-mingw32/lib/libc++utilities.a /usr/i686-w64-mingw32/lib/libQt5Network.a /usr/i686-w64-mingw32/lib/libQt5Svg.a /usr/i686-w64-mingw32/lib/libQt5Widgets.a /usr/i686-w64-mingw32/lib/libQt5Gui.a -lz /usr/i686-w64-mingw32/lib/libQt5Core.a /usr/i686-w64-mingw32/lib/libqtutilities.a /usr/i686-w64-mingw32/lib/libQt5Widgets.a /usr/i686-w64-mingw32/lib/libQt5Gui.a -Wl,-Bstatic -lpng16 -lharfbuzz -lfreetype -lharfbuzz -lfreetype -lglib-2.0 -lintl -lole32 -lwinmm -lshlwapi -lpcre -lintl -lole32 -lwinmm -lshlwapi -lpcre -lgraphite2 -lbz2 /usr/i686-w64-mingw32/lib/libc++utilities.a /usr/i686-w64-mingw32/lib/libQt5Network.a /usr/i686-w64-mingw32/lib/libQt5Concurrent.a /usr/i686-w64-mingw32/lib/libQt5Core.a /usr/i686-w64-mingw32/lib/libQt5Core.a -lmpr -lpcre2-16 -liconv -ldnsapi -liphlpapi -lcrypt32 -lssl -lcrypto -lcrypt32 -ldnsapi -liphlpapi -ldnsapi -liphlpapi -lcrypt32 -lssl -lcrypto -lcrypt32 -ldnsapi -liphlpapi -lz -lws2_32 -lQt5EventDispatcherSupport -lQt5FontDatabaseSupport -lQt5ThemeSupport -lQt5AccessibilitySupport -lwinspool -lwtsapi32 -lQt5WindowsUIAutomationSupport -ljpeg -L/usr/i686-w64-mingw32/lib -lQt5Svg -lQt5Widgets -lQt5Gui -lm -lglib-2.0 -lintl -lshlwapi -lpcre -lgraphite2 -lm -lglib-2.0 -lintl -lshlwapi -lpcre -lgraphite2 -lQt5Core -lz -lpcre2-16 -liconv -lversion -lnetapi32 -luserenv -luxtheme -ldwmapi -lopengl32 -lgdi32 -lcomdlg32 -loleaut32 -limm32 -lws2_32 -lkernel32 -luser32 -luuid -lole32 -ladvapi32 -lwinmm -lshell32 -ljpeg -lpng -lharfbuzz -lfreetype -lharfbuzz -lfreetype -lbz2 -lglu32 -lopengl32 -lgdi32 -luser32 -lkernel32 -luser32 -lgdi32 -lwinspool -lshell32 -lole32 -loleaut32 -luuid -lcomdlg32 -ladvapi32
```

The problem is the `-lz` between `-Wl,-Bdynamic` and `-Wl,-Bstatic`. Somehow I need to tell CMake not to produce `-Wl,-Bdynamic`. This was always the case but now seems to mess things.

I'm not sure why I only see this issue with Syncthing Tray and not the other of my applications. Maybe the order of the flags is kind of flaky after all.

By the way, here it also leads so a linker error:

```
[ 96%] Linking CXX executable syncthingtray.exe
/usr/lib/gcc/i686-w64-mingw32/8.3.0/../../../../i686-w64-mingw32/bin/ld: /usr/i686-w64-mingw32/lib/libz.a(deflate.o):(.text+0x1a20): multiple definition of `deflate'; /usr/i686-w64-mingw32/lib/libz.dll.a(d000012.o):(.text+0x0): first def
ined here
/usr/lib/gcc/i686-w64-mingw32/8.3.0/../../../../i686-w64-mingw32/bin/ld: /usr/i686-w64-mingw32/lib/libz.a(deflate.o):(.text+0x2cb0): multiple definition of `deflateEnd'; /usr/i686-w64-mingw32/lib/libz.dll.a(d000015.o):(.text+0x0): first defined here
/usr/lib/gcc/i686-w64-mingw32/8.3.0/../../../../i686-w64-mingw32/bin/ld: /usr/i686-w64-mingw32/lib/libz.a(deflate.o):(.text+0x2d60): multiple definition of `deflateInit2_'; /usr/i686-w64-mingw32/lib/libz.dll.a(d000017.o):(.text+0x0): first defined here
/usr/lib/gcc/i686-w64-mingw32/8.3.0/../../../../i686-w64-mingw32/bin/ld: /usr/i686-w64-mingw32/lib/libz.a(deflate.o):(.text+0x3060): multiple definition of `deflateInit_'; /usr/i686-w64-mingw32/lib/libz.dll.a(d000018.o):(.text+0x0): first defined here
/usr/lib/gcc/i686-w64-mingw32/8.3.0/../../../../i686-w64-mingw32/bin/ld: /usr/i686-w64-mingw32/lib/libz.a(inflate.o):(.text+0x250): multiple definition of `inflateReset'; /usr/i686-w64-mingw32/lib/libz.dll.a(d000074.o):(.text+0x0): first defined here
/usr/lib/gcc/i686-w64-mingw32/8.3.0/../../../../i686-w64-mingw32/bin/ld: /usr/i686-w64-mingw32/lib/libz.a(inflate.o):(.text+0x330): multiple definition of `inflateInit2_'; /usr/i686-w64-mingw32/lib/libz.dll.a(d000070.o):(.text+0x0): first defined here
/usr/lib/gcc/i686-w64-mingw32/8.3.0/../../../../i686-w64-mingw32/bin/ld: /usr/i686-w64-mingw32/lib/libz.a(inflate.o):(.text+0x440): multiple definition of `inflateInit_'; /usr/i686-w64-mingw32/lib/libz.dll.a(d000071.o):(.text+0x0): first defined here
/usr/lib/gcc/i686-w64-mingw32/8.3.0/../../../../i686-w64-mingw32/bin/ld: /usr/i686-w64-mingw32/lib/libz.a(inflate.o):(.text+0x4e0): multiple definition of `inflate'; /usr/i686-w64-mingw32/lib/libz.dll.a(d000061.o):(.text+0x0): first defined here
/usr/lib/gcc/i686-w64-mingw32/8.3.0/../../../../i686-w64-mingw32/bin/ld: /usr/i686-w64-mingw32/lib/libz.a(inflate.o):(.text+0x2470): multiple definition of `inflateEnd'; /usr/i686-w64-mingw32/lib/libz.dll.a(d000067.o):(.text+0x0): first defined here
/usr/lib/gcc/i686-w64-mingw32/8.3.0/../../../../i686-w64-mingw32/bin/ld: /usr/i686-w64-mingw32/lib/libz.a(inflate.o):(.text+0x2550): multiple definition of `inflateSetDictionary'; /usr/i686-w64-mingw32/lib/libz.dll.a(d000077.o):(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
```

Not sure how it could produce a binary actually linking against the dynamic version in your case.

**Comment by ypnos** [comment] 2019-03-07 10:46
It seems you are observing with CMake what I had observed with QMake. Interestingly, I did not have that with the Debug build, only Release (IIRC).

Was `--as-needed` linker option used?

**Comment by Martchus** [comment] 2019-03-07 13:03
Right, I actually did a debug build of Syncthing Tray against Qt 5.12.1 some time ago and didn't run into the issue, too.

And qmake is still not working for you? Because mingw-w64-qt5-tools builds I assume not *every* qmake project is affected. If you send me the link to your project I could try to reproduce it when I find the time (and motivation).

Until I find the time to fix my hack I'll add another hack on top of it: https://github.com/Martchus/PKGBUILDs/commit/f00b18276dd49132e71f4b3ff5274e502d7f8e3d#diff-76e971273c24ffaf268ac46728e1523cR56

Not very nice the "it works" at least :-)

**Comment by Martchus** [comment] 2019-03-23 16:50
Seems like `-Wl,-Bdynamic` is added internally by CMake. I tried different combinations of `LINK_SEARCH_END_STATIC` and `LINK_SEARCH_START_STATIC`. Those variables definitely influence this behavior of CMake. So far I always enabled `LINK_SEARCH_START_STATIC` in accordance with passing the `-static` flag. When playing around I could prevent the particular occurrence of `-Wl,-Bdynamic` by disabling `LINK_SEARCH_START_STATIC`. The problem is that I've got the `-Wl,-Bdynamic` not on a lot of other placed in the linker line.

So I'm coming up with yet another workaround: Creating an imported target for every god damn library we link against and setting its `IMPORTED_LOCATION` to the absolute library path determined using `find_library`. That seems to work. I only have to update the patches.

**Comment by Martchus** [comment] 2019-03-26 20:37
The CMake issue is fixed on latest master. Note that there's right now another issue with CMake affecting the build: https://aur.archlinux.org/packages/mingw-w64-cmake

So I'm closing the issue. I still can not reproduce the qmake issue.

**Comment by ypnos** [comment] 2019-03-27 13:46
Hello Martchus,

sorry for being away/silent for a while. It is funny that you mention this problem with CMake 3.14, as this problem or a similar one is one of the reasons to make me switch from qmake to CMake. What qmake does is use `-isystem` instead of `-I` and the messages, e.g. stdlib.h not found, are a result. I patched the Makefiles to avoid this problem.

I will also try again and reproduce the other problem with qmake when I get around to it. I shelved qmake for the time being but I can go back to an older revision and have a look.

**Comment by Martchus** [comment] 2019-05-02 23:22
see https://github.com/Martchus/PKGBUILDs/issues/94#issuecomment-488866532

**Comment by Martchus** [comment] 2020-11-08 00:15
Maybe this is still broken when using qmake. Because I don't use qmake except for building Qt itself I don't care much. Additionally, I'm focusing on Qt 6 now. So I'm closing the issue as it is unlikely that I'm taking the effort to fix this.

**Closed by Martchus** 2020-11-08 00:15 UTC
Labels: bug
