### ISSUE TITLE
RCC: Error ... Cannot find file

### ISSUE THREAD

**Issue by mdimura** [Martchus/PKGBUILDs#80] opened 2018-11-07 14:06 UTC
I get an error trying to build [Qt Main Window Application Example](https://github.com/qt/qtbase/tree/5.11/examples/widgets/mainwindows/mainwindow) using `mingw-w64-qt5-base 5.11.2-1` package (installed from repository):
```
$ x86_64-w64-mingw32-qmake-qt5 
Info: creating stash file /home/devel/application/.qmake.stash
QIODevice::seek: Cannot call seek on a sequential device
QIODevice::seek: Cannot call seek on a sequential device
QIODevice::seek: Cannot call seek on a sequential device
QIODevice::seek: Cannot call seek on a sequential device
QIODevice::seek: Cannot call seek on a sequential device
QIODevice::seek: Cannot call seek on a sequential device
QIODevice::seek: Cannot call seek on a sequential device
RCC: Error in 'application.qrc': Cannot find file 'images/copy.png'
RCC: Error in 'application.qrc': Cannot find file 'images/cut.png'
RCC: Error in 'application.qrc': Cannot find file 'images/new.png'
RCC: Error in 'application.qrc': Cannot find file 'images/open.png'
RCC: Error in 'application.qrc': Cannot find file 'images/paste.png'
RCC: Error in 'application.qrc': Cannot find file 'images/save.png'
RCC: Warning: No resources in 'application.qrc'.
RCC: Error in 'application.qrc': Cannot find file 'images/copy.png'
RCC: Error in 'application.qrc': Cannot find file 'images/cut.png'
RCC: Error in 'application.qrc': Cannot find file 'images/new.png'
RCC: Error in 'application.qrc': Cannot find file 'images/open.png'
RCC: Error in 'application.qrc': Cannot find file 'images/paste.png'
RCC: Error in 'application.qrc': Cannot find file 'images/save.png'
RCC: Warning: No resources in 'application.qrc'.
```
dowgrading to mingw-w64-qt5-base-5.10.0-1-x86_64 helps.
full script to reproduce the error:
```
git clone git://code.qt.io/qt/qtbase.git
cp -r qtbase/examples/widgets/mainwindows/application ./
cd application
x86_64-w64-mingw32-qmake-qt5
```

**Comment by Martchus** [comment] 2018-11-07 21:29
Can't reproduce:

```
[martchus@martchus-arch qt5]$ export LANG=C
[martchus@martchus-arch qt5]$ git -C qtbase checkout origin/5.11.2
HEAD is now at b0dce506cc add buildsystem+qmake changelog
[martchus@martchus-arch qt5]$ pacman -Qi mingw-w64-qt5-base
Name            : mingw-w64-qt5-base
Version         : 5.11.2-2
...
[martchus@martchus-arch qt5]$ cp -r qtbase/examples/widgets/mainwindows/application ./
[martchus@martchus-arch qt5]$  cd /run/media/devel/src/qt5/application
[martchus@martchus-arch application]$ x86_64-w64-mingw32-qmake-qt5
Info: creating stash file /run/media/devel/src/qt5/application/.qmake.stash
[martchus@martchus-arch application]$ make -j4
make -f Makefile.Release
make[1]: Verzeichnis „/run/media/devel/src/qt5/application“ wird betreten
x86_64-w64-mingw32-g++ -c -pipe -pipe -g -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions --param=ssp-buffer-size=4 -fno-keep-inline-dllexport -fpch-preprocess -O2 -Wall -W -Wextra -mthreads -DUNICODE -D_UNICODE -DMINGW_HAS_SECURE_API=1 -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_NEEDS_QMAIN -I. -isystem /usr/x86_64-w64-mingw32/include/qt -isystem /usr/x86_64-w64-mingw32/include/qt/QtWidgets -isystem /usr/x86_64-w64-mingw32/include/qt/QtGui -isystem /usr/x86_64-w64-mingw32/include/qt/QtCore -Irelease -I/usr/x86_64-w64-mingw32/lib/qt/mkspecs/win32-g++  -o release/main.o main.cpp
x86_64-w64-mingw32-g++ -c -pipe -pipe -g -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions --param=ssp-buffer-size=4 -fno-keep-inline-dllexport -fpch-preprocess -O2 -Wall -W -Wextra -mthreads -DUNICODE -D_UNICODE -DMINGW_HAS_SECURE_API=1 -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_NEEDS_QMAIN -I. -isystem /usr/x86_64-w64-mingw32/include/qt -isystem /usr/x86_64-w64-mingw32/include/qt/QtWidgets -isystem /usr/x86_64-w64-mingw32/include/qt/QtGui -isystem /usr/x86_64-w64-mingw32/include/qt/QtCore -Irelease -I/usr/x86_64-w64-mingw32/lib/qt/mkspecs/win32-g++  -o release/mainwindow.o mainwindow.cpp
/usr/x86_64-w64-mingw32/lib/qt/bin/rcc -name application application.qrc -o release/qrc_application.cpp
x86_64-w64-mingw32-g++ -pipe -pipe -g -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions --param=ssp-buffer-size=4 -fno-keep-inline-dllexport -fpch-preprocess -O2 -Wall -W -Wextra -dM -E -o release/moc_predefs.h /usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/data/dummy.cpp
x86_64-w64-mingw32-g++ -c -pipe -pipe -g -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions --param=ssp-buffer-size=4 -fno-keep-inline-dllexport -fpch-preprocess -O2 -Wall -W -Wextra -mthreads -DUNICODE -D_UNICODE -DMINGW_HAS_SECURE_API=1 -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_NEEDS_QMAIN -I. -isystem /usr/x86_64-w64-mingw32/include/qt -isystem /usr/x86_64-w64-mingw32/include/qt/QtWidgets -isystem /usr/x86_64-w64-mingw32/include/qt/QtGui -isystem /usr/x86_64-w64-mingw32/include/qt/QtCore -Irelease -I/usr/x86_64-w64-mingw32/lib/qt/mkspecs/win32-g++  -o release/qrc_application.o release/qrc_application.cpp
/usr/x86_64-w64-mingw32/lib/qt/bin/moc -DUNICODE -D_UNICODE -DMINGW_HAS_SECURE_API=1 -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_NEEDS_QMAIN --include /run/media/devel/src/qt5/application/release/moc_predefs.h -I/usr/x86_64-w64-mingw32/lib/qt/mkspecs/win32-g++ -I/run/media/devel/src/qt5/application -I/usr/x86_64-w64-mingw32/include/qt -I/usr/x86_64-w64-mingw32/include/qt/QtWidgets -I/usr/x86_64-w64-mingw32/include/qt/QtGui -I/usr/x86_64-w64-mingw32/include/qt/QtCore -I/usr/x86_64-w64-mingw32/include/c++/8.2.0 -I/usr/x86_64-w64-mingw32/include/c++/8.2.0/x86_64-w64-mingw32 -I/usr/x86_64-w64-mingw32/include/c++/8.2.0/backward -I/usr/lib/gcc/x86_64-w64-mingw32/8.2.0/include -I/usr/lib/gcc/x86_64-w64-mingw32/8.2.0/include-fixed -I/usr/x86_64-w64-mingw32/include mainwindow.h -o release/moc_mainwindow.cpp
x86_64-w64-mingw32-g++ -c -pipe -pipe -g -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions --param=ssp-buffer-size=4 -fno-keep-inline-dllexport -fpch-preprocess -O2 -Wall -W -Wextra -mthreads -DUNICODE -D_UNICODE -DMINGW_HAS_SECURE_API=1 -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_NEEDS_QMAIN -I. -isystem /usr/x86_64-w64-mingw32/include/qt -isystem /usr/x86_64-w64-mingw32/include/qt/QtWidgets -isystem /usr/x86_64-w64-mingw32/include/qt/QtGui -isystem /usr/x86_64-w64-mingw32/include/qt/QtCore -Irelease -I/usr/x86_64-w64-mingw32/lib/qt/mkspecs/win32-g++  -o release/moc_mainwindow.o release/moc_mainwindow.cpp
x86_64-w64-mingw32-g++ -g -Wl,-subsystem,windows -mthreads -o release/application.exe release/main.o release/mainwindow.o release/qrc_application.o release/moc_mainwindow.o  -lglu32 -lopengl32 -lgdi32 -luser32 -lmingw32 -lqt5main -lQt5Widgets -lQt5Gui -lQt5Core
[martchus@martchus-arch application]$ x86_64-w64-mingw32-win release/application.exe 
x86_64-w64-mingw32-windeployqt-qt5  x86_64-w64-mingw32-windmc           x86_64-w64-mingw32-windres          x86_64-w64-mingw32-wine             
[martchus@martchus-arch application]$ x86_64-w64-mingw32-wine release/application.exe 
0025:err:ntoskrnl:IoCreateDriver failed to insert driver L"\\Driver\\WineHID" in tree
002e:fixme:dwmapi:DwmIsCompositionEnabled 0x33c2f0
```

When starting the application with wine, the icons included via the qrc file are shown.

**Comment by mdimura** [comment] 2018-11-08 17:11
Here is the Dockerfile, which allows to reproduce the error:
[Dockerfile.txt](https://github.com/Martchus/PKGBUILDs/files/2562761/Dockerfile.txt)

**Comment by mdimura** [comment] 2018-11-09 12:57
Yes, you a right, apparently it's a known [docker bug](https://github.com/docker/for-linux/issues/208). Thank you for your answers!

**Comment by Martchus** [comment] 2018-11-09 13:01
You're welcome. I'm closing then. And I've noticed that this is likely for your [docker-mingw-qt5](https://github.com/mdimura/docker-mingw-qt5) project. I'll add a link to it in the README.md.

(note that https://github.com/Martchus/PKGBUILDs/issues/54#issuecomment-367995563 is related)

**Closed by Martchus** 2018-11-09 13:01 UTC
