### ISSUE TITLE
syncthingtray test 2 fails

### ISSUE THREAD

**Issue by RlndVt** [Martchus/PKGBUILDs#102] opened 2019-08-31 14:26 UTC
I get the following error when attempting to install syncthingtray from the aur:

```
2: Test command: /home/$user/.cache/yay/syncthingtray/src/syncthingtray-0.10.0/cli/syncthingctl_tests "-p" "/home/$user/.cache/yay/syncthingtray/src/syncthingtray-0.10.0/cli/testfiles" "-w" "/home/$user/.cache/yay/syncthingtray/src/syncthingtray-0.10.0/cli/testworkingdir" "-a" "/home/$user/.cache/yay/syncthingtray/src/syncthingtray-0.10.0/cli/syncthingctl"
2: Test timeout computed to be: 10000000
2: /home/$user/.cache/yay/syncthingtray/src/syncthingtray-0.10.0/cli/testfiles/
2: /home/$user/.cache/yay/syncthingtray/src/syncthingtray-0.10.0/cli/testfiles/
2: ./testfiles/
2: Directory used to store working copies:
2: /home/$user/.cache/yay/syncthingtray/src/syncthingtray-0.10.0/cli/testworkingdir/
2: Executing test cases ...
2: .
2:  - Setup configuration for Syncthing tests ...
2:  - Using timeout factor 3
2: 
2:  - Launching Syncthing: syncthing -gui-address=http://localhost:63711 -gui-apikey=syncthingtestinstance -home=/home/$user/.cache/yay/syncthingtray/src/syncthingtray-0.10.0/cli/testworkingdir/testconfig -no-browser -verbose
2: 
2: Waiting till Syncthing GUI becomes available ...[monitor] 16:01:38 INFO: Starting syncthing
2: [start] 16:01:38 INFO: syncthing v1.2.1 "Fermium Flea" (go1.12.8 linux-amd64) builduser@svetlemodry 2019-08-15 18:23:49 UTC
2: [start] 16:01:38 INFO: Generating ECDSA key and certificate for syncthing...
2: [start] 16:01:38 INFO: Archiving a copy of old config file format at: /home/$user/.cache/yay/syncthingtray/src/syncthingtray-0.10.0/cli/testworkingdir/testconfig/config.xml.v28
2: [TOF5R] 16:01:38 INFO: My ID: [REDACTED]
2: [TOF5R] 16:01:39 INFO: Single thread SHA256 performance is 431 MB/s using minio/sha256-simd (375 MB/s using crypto/sha256).
2: [TOF5R] 16:01:39 VERBOSE: Starting up (/home/$user/.cache/yay/syncthingtray/src/syncthingtray-0.10.0/cli/testworkingdir/testconfig)
2: [TOF5R] 16:01:39 INFO: Hashing performance is 354.97 MB/s
2: [TOF5R] 16:01:39 INFO: No stored folder metadata for "test1": recalculating
2: [TOF5R] 16:01:39 INFO: Ready to synchronize test1 (sendreceive)
2: [TOF5R] 16:01:39 INFO: Overall send rate is unlimited, receive rate is unlimited
2: [TOF5R] 16:01:39 INFO: Using discovery server https://discovery.syncthing.net/v2/?noannounce&id=LYXKCHX-VI3NYZR-ALCJBHF-WMZYSPK-QG6QJA3-MPFYMSO-U56GTUK-NA2MIAW
2: [TOF5R] 16:01:39 INFO: Using discovery server https://discovery-v4.syncthing.net/v2/?nolookup&id=LYXKCHX-VI3NYZR-ALCJBHF-WMZYSPK-QG6QJA3-MPFYMSO-U56GTUK-NA2MIAW
2: [TOF5R] 16:01:39 INFO: Using discovery server https://discovery-v6.syncthing.net/v2/?nolookup&id=LYXKCHX-VI3NYZR-ALCJBHF-WMZYSPK-QG6QJA3-MPFYMSO-U56GTUK-NA2MIAW
2: [TOF5R] 16:01:39 INFO: TCP listener (127.0.0.1:32452) starting
2: [TOF5R] 16:01:39 VERBOSE: Folder "test1" is now scan-waiting
2: [TOF5R] 16:01:39 VERBOSE: Folder "test1" is now scanning
2: [TOF5R] 16:01:39 INFO: Completed initial scan of sendreceive folder test1
2: [TOF5R] 16:01:39 VERBOSE: Folder "test1" is now idle
2: [TOF5R] 16:01:39 VERBOSE: Discovered device KQLXUYR-I23SV2N-J7UHBJS-PWUF6RB-X4RNE3P-NS7HMHK-O44YQQB-OWGYRAB at [tcp://[fe80::8ee:d831:b526:bb90%25wlp0s20f3]:22000 relay://90.190.250.61:22067/?id=U2SDWP7-2LBVIZM-2FA6HRO-CWSL4AE-JGLGFTE-XVUKIUJ-Z5BI22X-QK754AV&pingInterval=1m0s&networkTimeout=2m0s&sessionLimitBps=0&globalLimitBps=0&statusAddr=:22070&providedBy=Haha, Latvia has no relay quic://[fe80::8ee:d831:b526:bb90%25wlp0s20f3]:22000 quic://82.197.206.87:62088]
2: [TOF5R] 16:01:39 INFO: Loading HTTPS certificate: open /home/$user/.cache/yay/syncthingtray/src/syncthingtray-0.10.0/cli/testworkingdir/testconfig/https-cert.pem: no such file or directory
2: [TOF5R] 16:01:39 INFO: Creating new HTTPS certificate
2: [TOF5R] 16:01:39 INFO: GUI and API listening on 127.0.0.1:63711
2: [TOF5R] 16:01:39 INFO: Access the GUI via the following URL: http://localhost:63711/
2: - /home/$user/.cache/yay/syncthingtray/src/syncthingtray-0.10.0/cli/syncthingctl status --api-key syncthingtestinstance --url http://localhost:63711 --no-color
Overall statisticsg to http://localhost:63711 ...
2:    Status                        idle
2:       Global                        0 file(s), 0 dir(s), 0 bytes
2:       Local                         0 file(s), 0 dir(s), 0 bytes
2:    Incoming traffic              0 bytes
2:    Outgoing traffic              0 bytes
2:    Connected to                  no other devices
2:    Version                       syncthing v1.2.1 "Fermium Flea" (go1.12.8 linux-amd64) builduser@svetlemodry 2019-08-15 18:23:49 UTC
2: 
2: Directories
2:  - test2
2:    Label                         Test dir 2
2:    Path                          /tmp/some/path/2/
2:    Status                        paused
2:    Shared with                   Test dev 2
2:    Type                          Send & Receive
2:    Ignore permissions            no
2:    Auto-normalize                yes
2:    Rescan interval               365 d, file system watcher disabled
2: 
2:  - test1
2:    Path                          /tmp/some/path/1/
2:    Status                        idle
2:       Global                        0 file(s), 0 dir(s), 0 bytes
2:       Local                         0 file(s), 0 dir(s), 0 bytes
2:    Last scan time                2019-08-31 16:01:39.666
2:    Shared with                   Test dev 2
2:                                  Test dev 1
2:    Type                          Send & Receive
2:    Ignore permissions            no
2:    Auto-normalize                yes
2:    Rescan interval               2 h, file system watcher disabled
2: 
2: Devices
2:  - [REDACTED]
2:    ID                            [REDACTED]
2:    Status                        own device
2:    Addresses                     dynamic
2:    Compression                   metadata
2:    Last seen                     1970-01-01 01:00:00
2: 
2:  - Test dev 1
2:    ID                            6EIS2PN-J2IHWGS-AXS3YUL-HC5FT3K-77ZXTLL-AKQLJ4C-7SWVPUS-AZW4RQ4
2:    Status                        disconnected
2:    Addresses                     dynamic
2:    Compression                   metadata
2:    Last seen                     1970-01-01 01:00:00
2: 
2:  - Test dev 2
2:    ID                            MMGUI6U-WUEZQCP-XZZ6VYB-LCT4TVC-ER2HAVX-QYT6X7D-S6ZSG2B-323KLQ7
2:    Status                        paused
2:    Addresses                     tcp://192.168.2.2:22001
2:    Compression                   metadata
2:    Last seen                     1970-01-01 01:00:00
2: 
2: F
2:  - Waiting for Syncthing to terminate ...
2: 
2:  - Syncthing terminated with exit code 0.
2: 
2:  - Syncthing stdout during the testrun:
2: [TOF5R] 16:01:39 INFO: My name is "[REDACTED]"
2: [TOF5R] 16:01:39 INFO: Device MMGUI6U-WUEZQCP-XZZ6VYB-LCT4TVC-ER2HAVX-QYT6X7D-S6ZSG2B-323KLQ7 is "Test dev 2" at [tcp://192.168.2.2:22001]
2: [TOF5R] 16:01:39 INFO: Device 6EIS2PN-J2IHWGS-AXS3YUL-HC5FT3K-77ZXTLL-AKQLJ4C-7SWVPUS-AZW4RQ4 is "Test dev 1" at [dynamic]
2: [TOF5R] 16:01:39 VERBOSE: Startup complete
2: [TOF5R] 16:01:39 VERBOSE: Discovered device N4M4PLK-5IIWHWZ-Q4R5XKY-MZ5BLRU-VKGUGAQ-KMLSXZC-GSZCQJO-KNBHFQE at [kcp://[fe80::4bbe:9dba:6059:5092%25wlp0s20f3]:22020 kcp://82.197.206.87:22020 relay://94.130.123.126:22067/?id=XIQGKFH-LJA564N-OAGGFLR-JXLIFKZ-7IPYW52-B52TNBE-NPPVHFI-ZXFT7A4&pingInterval=1m0s&networkTimeout=2m0s&sessionLimitBps=0&globalLimitBps=0&statusAddr=:22070&providedBy=Deka-O tcp://[fe80::4bbe:9dba:6059:5092%25wlp0s20f3]:22000]
2: [TOF5R] 16:01:39 VERBOSE: Discovered device EJMJVVV-EHAJ2L7-VT6GLTX-D4E3WTM-IGRZED3-OJQ6LGD-6P2PGJ3-HAA5PAQ at [relay://5.9.16.38:22067/?id=2LUBIEC-ZNW4GMH-WKXLQUI-EZBCWDT-LRMPXL2-CIBPCB7-2KNIWFR-6T2WJQH&pingInterval=1m0s&networkTimeout=2m0s&sessionLimitBps=0&globalLimitBps=0&statusAddr=:22070&providedBy= tcp://[fe80::4ecc:6aff:fe90:4fe6%25wlp0s20f3]:18942 tcp://[fe80::4ecc:6aff:fe90:4fe6%25wlp0s20f3]:40729]
2: [TOF5R] 16:01:39 VERBOSE: Discovered device 3E2IORG-NVVZL3Y-DGPEZDS-VUOZPRG-Z3E5NL7-PGC6NR6-TQPOKYP-UJQHUQE at [tcp://[fe80::4ecc:6aff:fe90:4fe6%25wlp0s20f3]:22000 tcp://[fe80::4ecc:6aff:fe90:4fe6%25wlp0s20f3]:47132]
2: [monitor] 16:01:39 INFO: Signal 15 received; exiting
2: [TOF5R] 16:01:40 INFO: TCP listener (127.0.0.1:32452) shutting down
2: [TOF5R] 16:01:40 INFO: Exiting
2: 
2:  - Syncthing (re)started: 0 times
2:  - Syncthing exited:      0 times
2:  - Syncthing panicked:    0 times
2: 
2: 
2: !!!FAILURES!!!
2: Test Results:
2: Run:  1   Failures: 1   Errors: 0
2: 
2: 
2: 1) test: ApplicationTests::test (F) line: 146 /home/$user/.cache/yay/syncthingtray/src/syncthingtray-0.10.0/cli/tests/application.cpp
2: forced failure
2: - Line  - .* could not be found in output.
2: 
2: 
2: Tests failed
2/2 Test #2: syncthingctl_run_tests ...........***Failed    2.46 sec
```

Let me know if you need more info.

**Comment by Martchus** [comment] 2019-08-31 15:29
I haven't seen this for a while and actually hoped the test would be stable now. By the way, there shouldn't be the need to redact device IDs. This is supposed to use a test config and be independent from your regular setup.

**Comment by Aetf** [comment] 2021-01-10 02:27
I'm getting the same test failure again with the recent update:
```
test 2
    Start 2: syncthingctl_run_tests

2: Test command: /tmp/makepkg/syncthingtray/src/syncthingtray-1.1.1/cli/syncthingctl_tests
2: Test timeout computed to be: 10000000
2: /tmp/makepkg/syncthingtray/src/syncthingtray-1.1.1/cli/testfiles/
2: ./testfiles/
2: Directory used to store working copies:
2: ./testfiles/workingdir/
2: Executing test cases ...
2: .
2:  - Setup configuration for Syncthing tests ...
2:  - Using timeout factor 3
2: 
2:  - Launching Syncthing: syncthing -gui-address=http://localhost:60887 -gui-apikey=syncthingtestinstance -home=/tmp/makepkg/syncthingtray/src/syncthingtray-1.1.1/cli/testfiles/workingdir/testconfig -no-browser -verbose
2: 
2: Waiting till Syncthing GUI becomes available ...[start] 21:24:00 INFO: syncthing v1.12.1 "Fermium Flea" (go1.15.6 linux-amd64) builduser@archlinux 2021-01-06 13:32:47 UTC [noupgrade]
2: [start] 21:24:00 INFO: Generating ECDSA key and certificate for syncthing...
2: [start] 21:24:00 INFO: Archiving a copy of old config file format at: /tmp/makepkg/syncthingtray/src/syncthingtray-1.1.1/cli/testfiles/workingdir/testconfig/config.xml.v28
2: [6C3EY] 21:24:00 INFO: My ID: 6C3EYY2-JSOFNQJ-RKN4TQH-EWVNNBJ-JRBMNJR-Q6YIM2B-WR3QNS5-4G3OUAP
2: [6C3EY] 21:24:01 INFO: Single thread SHA256 performance is 451 MB/s using minio/sha256-simd (381 MB/s using crypto/sha256).
2: [6C3EY] 21:24:01 VERBOSE: Starting up (/tmp/makepkg/syncthingtray/src/syncthingtray-1.1.1/cli/testfiles/workingdir/testconfig)
2: [6C3EY] 21:24:01 INFO: Hashing performance is 377.42 MB/s
2: [6C3EY] 21:24:01 INFO: Running database migration 1...
2: [6C3EY] 21:24:01 INFO: Running database migration 2...
2: [6C3EY] 21:24:01 INFO: Running database migration 3...
2: [6C3EY] 21:24:01 INFO: Running database migration 5...
2: [6C3EY] 21:24:01 INFO: Running database migration 6...
2: [6C3EY] 21:24:01 INFO: Running database migration 7...
2: [6C3EY] 21:24:01 INFO: Running database migration 9...
2: [6C3EY] 21:24:01 INFO: Running database migration 10...
2: [6C3EY] 21:24:01 INFO: Running database migration 11...
2: [6C3EY] 21:24:01 INFO: Running database migration 13...
2: [6C3EY] 21:24:01 INFO: Running database migration 14...
2: [6C3EY] 21:24:01 INFO: Running database migration 15...
2: [6C3EY] 21:24:01 INFO: Compacting database after migration...
2: [6C3EY] 21:24:01 INFO: Overall send rate is unlimited, receive rate is unlimited
2: [6C3EY] 21:24:01 INFO: No stored folder metadata for "test1"; recalculating
2: [6C3EY] 21:24:01 INFO: Using discovery mechanism: global discovery server https://discovery.syncthing.net/v2/?noannounce&id=LYXKCHX-VI3NYZR-ALCJBHF-WMZYSPK-QG6QJA3-MPFYMSO-U56GTUK-NA2MIAW
2: [6C3EY] 21:24:01 INFO: Using discovery mechanism: global discovery server https://discovery-v4.syncthing.net/v2/?nolookup&id=LYXKCHX-VI3NYZR-ALCJBHF-WMZYSPK-QG6QJA3-MPFYMSO-U56GTUK-NA2MIAW
2: [6C3EY] 21:24:01 INFO: Using discovery mechanism: global discovery server https://discovery-v6.syncthing.net/v2/?nolookup&id=LYXKCHX-VI3NYZR-ALCJBHF-WMZYSPK-QG6QJA3-MPFYMSO-U56GTUK-NA2MIAW
2: [6C3EY] 21:24:01 INFO: Loading HTTPS certificate: open /tmp/makepkg/syncthingtray/src/syncthingtray-1.1.1/cli/testfiles/workingdir/testconfig/https-cert.pem: no such file or directory
2: [6C3EY] 21:24:01 INFO: Creating new HTTPS certificate
2: [6C3EY] 21:24:01 INFO: Using discovery mechanism: IPv4 local broadcast discovery on port 21027
2: [6C3EY] 21:24:01 INFO: Using discovery mechanism: IPv6 local multicast discovery on address [ff12::8384]:21027
2: [6C3EY] 21:24:01 INFO: Ready to synchronize test1 (sendreceive)
2: 2021/01/09 21:24:01 broadcastBeacon: Failed service 'Service@0xc0000be4c0 created by broadcastBeacon@0xc0001e8050/reader' (1.000000 failures of 2.000000), restarting: true, error: listen udp4 :21027: bind: address already in use
2: 2021/01/09 21:24:01 broadcastBeacon: Failed service 'Service@0xc0000be4c0 created by broadcastBeacon@0xc0001e8050/reader' (1.999998 failures of 2.000000), restarting: true, error: listen udp4 :21027: bind: address already in use
2: 2021/01/09 21:24:01 broadcastBeacon: Entering the backoff state.
2: [6C3EY] 21:24:01 VERBOSE: Folder "test1" is now scan-waiting
2: [6C3EY] 21:24:01 VERBOSE: Folder "test1" is now scanning
2: 2021/01/09 21:24:01 broadcastBeacon: Failed service 'Service@0xc0000be4c0 created by broadcastBeacon@0xc0001e8050/reader' (2.999997 failures of 2.000000), restarting: false, error: listen udp4 :21027: bind: address already in use
2: [6C3EY] 21:24:01 INFO: Completed initial scan of sendreceive folder test1
2: [6C3EY] 21:24:01 VERBOSE: Folder "test1" is now idle
2: [6C3EY] 21:24:01 INFO: GUI and API listening on 127.0.0.1:60887
2: [6C3EY] 21:24:01 INFO: Access the GUI via the following URL: http://localhost:60887/
2: [6C3EY] 21:24:01 INFO: My name is "Aetf-Arch-XPS"
2: - /tmp/makepkg/syncthingtray/src/syncthingtray-1.1.1/cli/syncthingctl status --api-key syncthingtestinstance --url http://localhost:60887 --no-color
Overall statisticsg to http://localhost:60887 ...
2:    Status                        idle
2:       Global                        0 file(s), 0 dir(s), 0 bytes
2:       Local                         0 file(s), 0 dir(s), 0 bytes
2:    Incoming traffic              0 bytes
2:    Outgoing traffic              0 bytes
2:    Connected to                  no other devices
2:    Version                       syncthing v1.12.1 "Fermium Flea" (go1.15.6 linux-amd64) builduser@archlinux 2021-01-06 13:32:47 UTC [noupgrade]
2: 
2: Directories
2:  - test2
2:    Label                         Test dir 2
2:    Path                          /tmp/some/path/2/
2:    Status                        paused
2:    Shared with                   Test dev 2
2:    Remote progress               all up-to-date
2:       Test dev 2                    0 bytes / 0 bytes (0 %)
2:    Type                          Send & Receive
2:    Ignore permissions            no
2:    Auto-normalize                yes
2:    Rescan interval               365 d, file system watcher disabled
2: 
2:  - test1
2:    Path                          /tmp/some/path/1/
2:    Status                        idle
2:       Global                        0 file(s), 0 dir(s), 0 bytes
2:       Local                         0 file(s), 0 dir(s), 0 bytes
2:    Last scan time                2021-01-09 21:24:01.532
2:    Shared with                   Test dev 2
2:                                  Test dev 1
2:    Remote progress               all up-to-date
2:       Test dev 2                    0 bytes / 0 bytes (100 %)
2:       Test dev 1                    0 bytes / 0 bytes (100 %)
2:    Type                          Send & Receive
2:    Ignore permissions            no
2:    Auto-normalize                yes
2:    Rescan interval               2 h, file system watcher disabled
2: 
2: Devices
2:  - Aetf-Arch-XPS
2:    ID                            6C3EYY2-JSOFNQJ-RKN4TQH-EWVNNBJ-JRBMNJR-Q6YIM2B-WR3QNS5-4G3OUAP
2:    Status                        own device
2:    Addresses                     dynamic
2:    Compression                   metadata
2: 
2:  - Test dev 1
2:    ID                            6EIS2PN-J2IHWGS-AXS3YUL-HC5FT3K-77ZXTLL-AKQLJ4C-7SWVPUS-AZW4RQ4
2:    Status                        disconnected
2:    Addresses                     dynamic
2:    Compression                   metadata
2: 
2:  - Test dev 2
2:    ID                            MMGUI6U-WUEZQCP-XZZ6VYB-LCT4TVC-ER2HAVX-QYT6X7D-S6ZSG2B-323KLQ7
2:    Status                        paused
2:    Addresses                     tcp://192.168.2.2:22001
2:    Compression                   metadata
2: 
2: F
2:  - Waiting for Syncthing to terminate ...
2: 
2:  - Syncthing terminated with exit code 0.
2: 
2:  - Syncthing stdout during the testrun:
2: [6C3EY] 21:24:01 INFO: Device MMGUI6U-WUEZQCP-XZZ6VYB-LCT4TVC-ER2HAVX-QYT6X7D-S6ZSG2B-323KLQ7 is "Test dev 2" at [tcp://192.168.2.2:22001]
2: [6C3EY] 21:24:01 INFO: Device 6EIS2PN-J2IHWGS-AXS3YUL-HC5FT3K-77ZXTLL-AKQLJ4C-7SWVPUS-AZW4RQ4 is "Test dev 1" at [dynamic]
2: [6C3EY] 21:24:01 VERBOSE: Startup complete
2: [6C3EY] 21:24:01 INFO: TCP listener (127.0.0.1:32452) starting
2: [6C3EY] 21:24:01 VERBOSE: Listen address tcp://localhost:32452 resolution has changed: lan addresses: [tcp://localhost:32452] wan addresses: [tcp://0.0.0.0:0 tcp://localhost:32452]
2: [6C3EY] 21:24:01 VERBOSE: Discovered device UPY42MB-KYPG6D2-XRVZR7K-CXYERHK-2KSYPYT-MDFXMUU-VWTJFLY-D6KX5A4 at [quic://[fe80::3113:8700:60b4:d276%25enp167s0u2u4]:22000 quic://192.168.50.254:22000 quic://192.168.122.1:22000 quic://10.144.175.24:22000 quic://172.18.0.1:22000 quic://172.17.0.1:22000 quic://73.144.153.55:22000 tcp://[fe80::3113:8700:60b4:d276%25enp167s0u2u4]:22000 tcp://192.168.50.254:22000 tcp://192.168.122.1:22000 tcp://10.144.175.24:22000 tcp://172.18.0.1:22000 tcp://172.17.0.1:22000 tcp://[fe80::3113:8700:60b4:d276%25enp167s0u2u4]:0 tcp://[fe80::3113:8700:60b4:d276%25enp167s0u2u4]:44748 tcp://[fe80::3113:8700:60b4:d276%25enp167s0u2u4]:64672 relay://193.219.28.151:443/?id=VDCRPDV-OOV5NWU-EYK4ACU-PJARLPT-YO3F3JT-ATGNOMT-L24QQ2V-PBOTRQI&pingInterval=1m0s&networkTimeout=2m0s&sessionLimitBps=0&globalLimitBps=0&statusAddr=:22070&providedBy=ICM UW]
2: [monitor] 21:24:01 INFO: Signal 15 received; exiting
2: [6C3EY] 21:24:01 INFO: Detected 1 NAT service
2: [6C3EY] 21:24:01 INFO: UPnP parse: dial tcp 192.168.50.1:34808: operation was canceled
2: [6C3EY] 21:24:01 INFO: UPnP parse: dial tcp 192.168.50.1:34808: operation was canceled
2: [6C3EY] 21:24:02 INFO: TCP listener (127.0.0.1:32452) shutting down
2: [6C3EY] 21:24:02 INFO: Exiting
2: 
2:  - Syncthing (re)started: 0 times
2:  - Syncthing exited:      0 times
2:  - Syncthing panicked:    0 times
2: 
2: 
2: !!!FAILURES!!!
2: Test Results:
2: Run:  1   Failures: 1   Errors: 0
2: 
2: 
2: 1) test: ApplicationTests::test (F) line: 146 cli/tests/application.cpp
2: forced failure
2: - Line  - .* could not be found in output.
2: 
2: 
2: Tests failed
2/2 Test #2: syncthingctl_run_tests ...........***Failed    2.51 sec
```

Actually, the test never worked for me on both my laptop and desktop machiens.

**Comment by Martchus** [comment] 2021-01-11 17:11
Seems like the order of the devices is random but the test expects a certain order. That's definitely something I should fix. Since devices and folders are now shown in alphabetical order within the web UI it would make sense to sort them within the CLI as well which should also stabilize this test.

**Comment by Martchus** [comment] 2021-01-11 17:51
Should be fixed with https://github.com/Martchus/syncthingtray/commit/2eaddb0464588eb6b2abaaabbc45c1049a9d2c1e

**Comment by afettouhi** [comment] 2021-04-07 09:08
Having this issue as well when building syncthingtray 1.1.4.

**Comment by Martchus** [comment] 2021-04-07 09:22
But you likely don't have the *very* same test failure which was caused by a sorting issue which should be fixed by now. Can you share the logs? Does is always fail in your case? As a workaround you can of course just disable running the testsuite.

By the way, I'm usually building my packages on a slow "AMD Athlon(tm) 5350 APU" on a system which runs also other services and do *not* run into timeouts.

**Comment by afettouhi** [comment] 2021-04-07 09:40
Yes, it fails every time. Here is the output when building it with `makepkg -c`

[Output.txt](https://github.com/Martchus/PKGBUILDs/files/6270534/Output.txt)

**Comment by Martchus** [comment] 2021-04-07 09:55
Looks like both tests (backend library and CLI) fail for the same reason: `Unable to request completion for device/directory MMGUI6U-WUEZQCP-XZZ6VYB-LCT4TVC-ER2HAVX-QYT6X7D-S6ZSG2B-323KLQ7/test2: Error transferring http://localhost:49668/rest/db/completion?device=MMGUI6U-WUEZQCP-XZZ6VYB-LCT4TVC-ER2HAVX-QYT6X7D-S6ZSG2B-323KLQ7&folder=test2 - server replied: Not Found`

In the test setup `MMGUI6U-WUEZQCP-XZZ6VYB-LCT4TVC-ER2HAVX-QYT6X7D-S6ZSG2B-323KLQ7` is suppoed to be a paused device and `test2` a paused directory shared with that device (see https://github.com/Martchus/syncthingtray/blob/master/cli/testfiles/expected-status.txt).

Is something else running on port 49668?

**Comment by Martchus** [comment] 2021-04-07 10:11
I now get the same when testing against Syncthing 1.15.1. (I conducted my own build yesterday when there was still the previous version in the repos.)

So it looks like until the tests are fixed you really have to ignore the failures and hope that nothing is actually broken. Note that this could actually also be caused by an unintended change within Syncthing itself regarding the behavior of paused devs/dirs and querying their completion state.

**Comment by Martchus** [comment] 2021-04-07 11:22
I'm closing this issue because the original problem with the tests has been fixed and now another user created a separate ticket: https://github.com/Martchus/PKGBUILDs/issues/132

**Closed by Martchus** 2021-04-07 11:22 UTC
